# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91687251195312b586e1df12a8a3994ef4ee2231869bf789046570a1177eeb1c9f35c72eb29a16014c0cc04e7006ed792e16b8b509633458f8e3ea7f2260fb6b

test:
  secret_key_base: 5c0ac71296b72a1d6c4900bcfd7807693549dd391c8618d5cd9241917e5c3991039b05381ca3e97fa6db4eea684451d50bd963c2f62f5122f2cb56313dfad37e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
